global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: 'murilo'
    static_configs:
      - targets: ['node-exporter:9100']
